version: "3.8"

services:
  client:
    image: coderfair-client-dev
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: coderfair-client-dev-container
  server:
    image: coderfair-backend-dev
    # build:
    #   context: .
    #   dockerfile: dev.Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./backend:/usr/src/app/backend
    container_name: coderfair-backend-server-dev-container
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    container_name: coderfair-db-dev-container
# docker run -it -v "$(pwd):/usr/src/app/backend" toolkit-backend-dev bash

volumes:
  # Fix missing linux modules in container
  # Link: https://github.com/vitejs/vite/discussions/15532
  node_modules:

  # Persist data
  postgres_data:
